repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: '.*\.(txt|csv)'
      - id: end-of-file-fixer
        exclude: '.*\.(txt|csv)'
      - id: check-yaml
        exclude: '.*\.(txt|csv)'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        name: pyupgrade (.py files)

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: nbstripout (.ipynb files)

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-pyupgrade
        args: [ '--py39-plus' ]
        name: pyupgrade (.ipynb files)
      - id: nbqa-ruff
        name: ruff (.ipynb files)
        args: [ "--fix", "--exit-non-zero-on-fix" ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.14.3'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.7
    hooks:
      - id: uv-lock
        name: uv-lock
        description: Update uv.lock file
      - id: uv-export
        name: uv-export
        description: Export requirements for compatibility

  - repo: local
    hooks:
      - id: pyclean
        name: pyclean
        entry: uvx pyclean .
        language: system
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uvx pytest
        language: system
        pass_filenames: false
        always_run: true
